[project]
name = "nn-laser-stabilizer"
version = "7.0.0"
description = "Neural network based laser stabilizer"
authors = [
    { name = "Artem Gemuzov", email = "a.gemuzov@g.nsu.ru" }
]
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
