type: td3
gamma: 0.98
policy_noise: 0.1
noise_clip: 0.25
tau: 0.005
policy_freq: 2

actor:
  network:
    _include: "{CONFIGS_DIR}/networks/lstm_64_2"
  optimizer:
    lr: 0.001

critic:
  network:
    _include: "{CONFIGS_DIR}/networks/lstm_64_2"
  optimizer:
    lr: 0.001
