type: td3
gamma: 0.99
policy_noise: 0.2
noise_clip: 0.5
tau: 0.005
policy_freq: 2

actor:
  network:
    _include: "{CONFIGS_DIR}/networks/mlp_256_256"
  optimizer:
    lr: 0.001

critic:
  network:
    _include: "{CONFIGS_DIR}/networks/mlp_256_256"
  optimizer:
    lr: 0.001
