name: NeuralPIDEnv
args:
  port: COM3
  timeout: 0.1
  baudrate: 115200

  log_dir: "env_logs"
  log_file: env.log

  setpoint: 1200
  auto_determine_setpoint: false
  setpoint_determination_steps: 6000
  setpoint_determination_max_value: 2000
  setpoint_determination_factor: 0.1

  control_min: 0
  control_max: 4095

  process_variable_max: 2000
