name: PidDeltaTuning
wrappers:
  step_tracking:
    time_multiplier: 1e6
  info_logging:
    log_dir: "env_logs"
    log_file: env.log
args:
  port: COM3
  timeout: 0.1
  baudrate: 115200

  log_connection: true

  setpoint: 1200
  auto_determine_setpoint: false
  setpoint_determination_steps: 6000
  setpoint_determination_max_value: 2000
  setpoint_determination_factor: 0.1

  warmup_steps: 1000
  block_size: 200
  burn_in_steps: 100
  control_output_min_threshold: 200.0
  control_output_max_threshold: 4096.0
  force_min_value: 2000
  force_max_value: 2500
  default_min: 0
  default_max: 4095

  kp_min: 2.5
  kp_max: 12.5
  kp_start: 7.5
  kp_delta_scale: 0.01

  ki_min: 0.0
  ki_max: 20.0
  ki_start: 10.0
  ki_delta_scale: 0.01

  kd_min: 0.0
  kd_max: 0.005
  kd_start: 0.002
  kd_delta_scale: 0.001

  error_mean_normalization_factor: 100.0
  error_std_normalization_factor: 200.0
  
  precision_weight: 0.45
  stability_weight: 0.45
  action_weight: 0.1
