seed: 1

env:
  name: NeuralController
  wrappers:
    step_tracking:
      time_multiplier: 1e6
  args:
    backend:
      type: experimental
      port: COM3
      timeout: 0.1
      baudrate: 115200
      log_connection: true
      auto_determine_setpoint: false
      setpoint_determination_steps: 6000
      setpoint_determination_max_value: 2000
      setpoint_determination_factor: 0.1

    setpoint: 1200

    control_min: 0
    control_max: 4095
    reset_value: 2000
    reset_steps: 1000

    action:
      type: delta
      max_delta: 25

    process_variable_min: 1000
    process_variable_max: 2000

    observe_prev_error: true
    observe_prev_prev_error: true
    observe_control_output: false

    normalize_obs: true

    reward:
      action_penalty: 0.0


training:
  train_start_step: 5_000        
  sync_start_step: 5_000        
  num_steps: -1
  log_frequency: 1
  log_dir: "."
  log_file: train.jsonl

exploration:
  type: pid
  steps: 25_000
  kp: 3.5
  ki: 11.0
  kd: 0.002
  dt: 0.005
  max_delta: 25.0

collector:
  _include: "{CONFIGS_DIR}/collectors/async"

evaluation:
  _include: "{CONFIGS_DIR}/common/evaluation_none"

buffer:
  _include: "{CONFIGS_DIR}/buffers/1000k"

sampler:
  _include: "{CONFIGS_DIR}/samplers/single"

algorithm:
  _include: "{CONFIGS_DIR}/algorithms/sac_default"