seed: 1

env:
  name: NeuralPIDDeltaEnv
  args:
    port: COM3
    timeout: 0.1
    baudrate: 115200
    log_connection: true

    log_dir: "."
    log_file: env.jsonl

    setpoint: 1200
    
    auto_determine_setpoint: false
    setpoint_determination_steps: 6000
    setpoint_determination_max_value: 2000
    setpoint_determination_factor: 0.1

    control_min: 0
    control_max: 4095
    max_control_delta: 30
    reset_value: 2000
    reset_steps: 1000

    process_variable_max: 10230

  normalize_obs: true
  normalize_reward: true

training:
  train_start_step: 5_000        
  sync_start_step: 5_000        
  num_steps: -1
  log_frequency: 1
  log_dir: "."
  log_file: train.jsonl

exploration:
  type: pid
  steps: 20_000
  kp: 3.5
  ki: 11.0
  kd: 0.002
  dt: 0.005
  max_delta: 30.0

collector:
  _include: "{CONFIGS_DIR}/collectors/async"

evaluation:
  _include: "{CONFIGS_DIR}/common/evaluation_none"

buffer:
  _include: "{CONFIGS_DIR}/buffers/100k"

sampler:
  _include: "{CONFIGS_DIR}/samplers/single"

algorithm:
  _include: "{CONFIGS_DIR}/algorithms/td3_neural_controller"