seed: 1

env:
  _include: "{CONFIGS_DIR}/envs/neural_controller"

training:
  _include: "{CONFIGS_DIR}/common/training_neural"

exploration:
  _include: "{CONFIGS_DIR}/common/exploration_ou"

collector:
  _include: "{CONFIGS_DIR}/collectors/async"

validation:
  _include: "{CONFIGS_DIR}/common/validation_none"

testing:
  _include: "{CONFIGS_DIR}/common/testing_none"

buffer:
  _include: "{CONFIGS_DIR}/buffers/100k"

sampler:
  _include: "{CONFIGS_DIR}/samplers/single"

algorithm:
  _include: "{CONFIGS_DIR}/algorithms/td3_default"
