experiment_name: neural_pid
seed: 1

env:
  name: NeuralPIDEnv
  args:
    port: COM3
    timeout: 0.1
    baudrate: 115200

    log_dir: "env_logs"
    log_file: env.log

    setpoint: 1200
    auto_determine_setpoint: false
    setpoint_determination_steps: 6000
    setpoint_determination_max_value: 2000
    setpoint_determination_factor: 0.1

    control_min: 0
    control_max: 4095

    process_variable_max: 2000

training:
  train_start_step: 2500
  sync_start_step: 2500
  num_steps: -1
  log_frequency: 1
  policy_freq: 2
  log_dir: "train_logs"
  log_file: train.log

exploration:
  type: random
  steps: 2650

collector:
  is_async: true
  sync_frequency: 10

validation:
  frequency: 0
  num_steps: 0

testing:
  num_steps: 0

buffer:
  capacity: 10000

sampler:
  type: single
  batch_size: 64

network:
  type: mlp
  mlp_hidden_sizes: [3]

loss:
  type: td3  
  gamma: 0.95
  policy_noise: 0.05
  noise_clip: 0.125

optimizer:
  actor_lr: 0.001
  critic_lr: 0.001
  tau: 0.005

