experiment_name: neural_pid
seed: 1

env:
  _include: "{CONFIGS_DIR}/envs/neural_pid"

training:
  _include: "{CONFIGS_DIR}/common/training_pid"

exploration:
  _include: "{CONFIGS_DIR}/common/exploration_random"

collector:
  _include: "{CONFIGS_DIR}/collectors/async"

evaluation:
  _include: "{CONFIGS_DIR}/common/evaluation_none"

buffer:
  _include: "{CONFIGS_DIR}/buffers/10k"

sampler:
  _include: "{CONFIGS_DIR}/samplers/single"

algorithm:
  _include: "{CONFIGS_DIR}/algorithms/td3_default"
  actor:
    network:
      _include: "{CONFIGS_DIR}/networks/mlp_3"
  critic:
    network:
      _include: "{CONFIGS_DIR}/networks/mlp_3"

