experiment_name: pendulum_no_vel
seed: 42

env:
  _include: {CONFIGS_DIR}/envs/pendulum_no_vel

buffer:
  _include: {CONFIGS_DIR}/buffers/100k

sampler:
  _include: {CONFIGS_DIR}/samplers/sequence

collector:
  _include: {CONFIGS_DIR}/collectors/sync

network:
  _include: {CONFIGS_DIR}/networks/lstm_64_2

updater:
  _include: {CONFIGS_DIR}/updaters/td3_pendulum

training:
  _include: {CONFIGS_DIR}/common/training_pendulum

exploration:
  _include: {CONFIGS_DIR}/common/exploration_random_pendulum

validation:
  _include: {CONFIGS_DIR}/common/validation_pendulum

testing:
  _include: {CONFIGS_DIR}/common/testing_pendulum
