experiment_name: pendulum
seed: 42

env:
  name: Pendulum-v1

buffer:
  capacity: 100000

sampler:
  type: sequence
  seq_len: 20
  batch_size: 64

collector:
  is_async: false
  collect_steps_per_iteration: 101

network:
  type: lstm
  lstm_hidden_size: 64
  lstm_num_layers: 2
  mlp_hidden_sizes: []

loss:
  gamma: 0.98
  policy_noise: 0.1
  noise_clip: 0.25

optimizer:
  actor_lr: 0.001
  critic_lr: 0.001
  tau: 0.005

training:
  initial_collect_steps: 2000
  num_training_steps: 20_000
  exploration_steps: 2000
  log_frequency: 100
  policy_freq: 2
  log_dir: "{EXPERIMENT_DIR}/logs"
  log_file: train.log

validation:
  frequency: 500
  num_steps: 200

testing:
  num_steps: 1000