experiment_name: pendulum
seed: 42

env:
  name: Pendulum-v1

buffer:
  capacity: 100000

sampler:
  type: sequence
  seq_len: 20
  batch_size: 64

collector:
  is_async: false
  collect_steps_per_iteration: 10

network:
  type: lstm
  lstm_hidden_size: 64
  lstm_num_layers: 2
  mlp_hidden_sizes: [256, 256]

updater:
  type: td3
  gamma: 0.98
  policy_noise: 0.1
  noise_clip: 0.25
  actor_lr: 0.001
  critic_lr: 0.001
  tau: 0.005
  policy_freq: 2

training:
  train_start_step: 2000
  sync_start_step: 2000
  num_steps: 20_000
  log_frequency: 100
  log_dir: "train_logs"
  log_file: train.log

exploration:
  type: random
  steps: 2000

validation:
  frequency: 500
  num_steps: 200

testing:
  num_steps: 1000