experiment_name: pendulum-v1
seed: 42

env:
  _include: "{CONFIGS_DIR}/envs/pendulum"

buffer:
  _include: "{CONFIGS_DIR}/buffers/1000k"

sampler:
  _include: "{CONFIGS_DIR}/samplers/single"

collector:
  _include: "{CONFIGS_DIR}/collectors/sync"

algorithm:
  _include: "{CONFIGS_DIR}/algorithms/sac_default"

training:
  _include: "{CONFIGS_DIR}/common/training_pendulum"

exploration:
  _include: "{CONFIGS_DIR}/common/exploration_random_pendulum"

evaluation:
  _include: "{CONFIGS_DIR}/common/evaluation_pendulum"
