experiment_name: pendulum
seed: 42

env:
  _include: "{CONFIGS_DIR}/envs/pendulum"

buffer:
  _include: "{CONFIGS_DIR}/buffers/100k"

sampler:
  _include: "{CONFIGS_DIR}/samplers/sequence"

collector:
  _include: "{CONFIGS_DIR}/collectors/sync"

algorithm:
  _include: "{CONFIGS_DIR}/algorithms/td3_pendulum"

training:
  _include: "{CONFIGS_DIR}/common/training_pendulum"

exploration:
  _include: "{CONFIGS_DIR}/common/exploration_random_pendulum"

evaluation:
  _include: "{CONFIGS_DIR}/common/evaluation_pendulum"
