experiment_name: pid_delta_tuning
seed: 1

env:
  _include: {CONFIGS_DIR}/envs/pid_delta_tuning

training:
  _include: {CONFIGS_DIR}/common/training_pid

exploration:
  _include: {CONFIGS_DIR}/common/exploration_random

collector:
  _include: {CONFIGS_DIR}/collectors/async

validation:
  _include: {CONFIGS_DIR}/common/validation_none

testing:
  _include: {CONFIGS_DIR}/common/testing_none

buffer:
  _include: {CONFIGS_DIR}/buffers/10k

sampler:
  _include: {CONFIGS_DIR}/samplers/single

network:
  _include: {CONFIGS_DIR}/networks/mlp_256_256

updater:
  _include: {CONFIGS_DIR}/updaters/td3_default
