_extends: train_async

experiment_name: pid_delta_tuning

env:
  name: PidDeltaTuningEnv
  args:
    use_mock: false
    port: COM3
    timeout: 0.1
    baudrate: 115200
    test_optimal_kp: 10.0
    test_optimal_ki: 17.5
    test_setpoint: 1200.0
    test_max_distance: 20.0
    test_noise_std: 30.0
    log_connection: false
    connection_log_dir: .
    connection_log_file: connection.log
    setpoint: 1200.0
    warmup_steps: 1000
    block_size: 100
    burn_in_steps: 20
    control_output_min_threshold: 200.0
    control_output_max_threshold: 4095.0
    force_min_value: 2000
    force_max_value: 2500
    default_min: 0
    default_max: 4095
    kp_min: 2.5
    kp_max: 12.5
    kp_start: 7.5
    ki_min: 0.0
    ki_max: 20.0
    ki_start: 10.0
    kd_min: 0.0
    kd_max: 0.0
    kd_start: 0.0
    error_mean_normalization_factor: 400.0
    error_std_normalization_factor: 300.0
    kp_delta_scale: 0.01
    ki_delta_scale: 0.01
    precision_weight: 0.4
    stability_weight: 0.4
    action_weight: 0.2
    log_dir: .
    log_file: env.log

