experiment_name: pid_delta_tuning
seed: 0

training:
  initial_collect_steps: 2000
  num_training_steps: 1_000_000_000
  exploration_steps: 2500
  log_frequency: 1
  policy_freq: 2
  log_dir: "{EXPERIMENT_DIR}/logs"
  log_file: train.log

validation:
  frequency: 0
  step_num_steps: 0
  final_num_steps: 0

env:
  name: PidDeltaTuningEnv
  args:
    use_mock: true
    port: COM3
    timeout: 0.1
    baudrate: 115200

    log_connection: false
    connection_log_dir: "{EXPERIMENT_DIR}/connection_logs"
    connection_log_file: connection.log

    setpoint: 1200.0
    warmup_steps: 1000
    block_size: 100
    burn_in_steps: 20
    control_output_min_threshold: 200.0
    control_output_max_threshold: 4095.0
    force_min_value: 2000
    force_max_value: 2500
    default_min: 0
    default_max: 4095

    kp_min: 2.5
    kp_max: 12.5
    kp_start: 7.5

    ki_min: 0.0
    ki_max: 20.0
    ki_start: 10.0

    kd_min: 0.0
    kd_max: 0.0
    kd_start: 0.0

    error_mean_normalization_factor: 200.0
    error_std_normalization_factor: 300.0

    kp_delta_scale: 0.01
    ki_delta_scale: 0.01
    precision_weight: 0.4
    stability_weight: 0.4
    action_weight: 0.2

    log_dir: "{EXPERIMENT_DIR}/env_logs"
    log_file: env.log

buffer:
  capacity: 10000

sampler:
  batch_size: 64

network:
  hidden_sizes: [256, 256]

loss:
  gamma: 0.98
  policy_noise: 0.1
  noise_clip: 0.25

optimizer:
  actor_lr: 0.001
  critic_lr: 0.001
  tau: 0.005

