experiment_name: pid_delta_tuning-inference
seed: 1

inference:
  actor_type: mlp
  actor_path: "{RESOURCES_DIR}/2025-11-25_15-51-58/actor.pth"
  num_steps: -1  
  log_frequency: 0

env:
  _include: {CONFIGS_DIR}/envs/pid_delta_tuning_recurrent
