experiment_name: neural_controller_delta_mlp_256_256
seed: 1

env:
  _include: "{CONFIGS_DIR}/envs/neural_pid_delta"

training:
  _include: "{CONFIGS_DIR}/common/training_neural"

exploration:
  _include: "{CONFIGS_DIR}/common/exploration_ou"

collector:
  _include: "{CONFIGS_DIR}/collectors/async"

evaluation:
  _include: "{CONFIGS_DIR}/common/evaluation_none"

buffer:
  _include: "{CONFIGS_DIR}/buffers/100k"

sampler:
  _include: "{CONFIGS_DIR}/samplers/single"

algorithm:
  _include: "{CONFIGS_DIR}/algorithms/td3_default"